### ISSUE TITLE
code duplication

### ISSUE THREAD

**Issue by MasseGuillaume** [sameerbhadouria/avdl2avsc-maven-plugin#1]
it's already implemented here
https://svn.apache.org/repos/asf/avro/trunk/lang/java/tools/src/main/java/org/apache/avro/tool/IdlToSchemataTool.java

**Comment by sameerbhadouria** [comment]
Although, this tool provides similar functionality, the usage is different. 
What we have here is a convenient way to use the .avsc schema generation functionality from a maven project file.

Thanks for sharing that link!

**Comment by MasseGuillaume** [comment]
yep, It's not that  much ;-)
